### ISSUE TITLE
Raw markdown shows in thread summary

### ISSUE THREAD

**Issue by dbj** [dailydrip/firestorm#100]
When there is a markdown link in the body of a post for a thread, when on the [category summary](https://forum.firestormforum.org/categories/3) page and the thread summary is shown, the link in the body is in raw format rather than interpreted markdown.

![image](https://user-images.githubusercontent.com/63229/28030251-cf345fce-6557-11e7-940e-7790f7ba7a66.png)

**Comment by knewter** [comment]
I made this change on purpose. need to make it smarter or else that page got weird if you posted an image, for example. so on the index we don't parse right now
