### ISSUE TITLE
Question about style of file placement. 

### ISSUE THREAD

**Issue by digitalcake** [dailydrip/firestorm#104]
I noticed markdown.ex was not nested inside it's respective folder while on the other hand forums.ex was. I'm thinking that was possibly a mistake ("or not IDK"), but it tickled my brain and I wanted to understand your reasoning for doing it one way or the other.

**Comment by knewter** [comment]
I think forums.ex should not be nested inside the forums folder but that's how Phoenix generators place that file. I left it like that to stick with their conventions, but in general don't prefer the style :)
