### ISSUE TITLE
Layout via Native CSS Grid Layout?

### ISSUE THREAD

**Issue by SoreGums** [dailydrip/firestorm#106]
Is a css grid based layout a want?

Simpler to specify layouts and helps with accessibility as there is a lot less extra html markup.

I haven't looked into the html as yet.

looks fairly simple though, just take time to figure it out, something I'm keen to work on.
Thought I'd ask first as there might already be things in motion etc

**Comment by OvermindDL1** [comment]
> Is a css grid based layout a want?

Not well supported by evergreen browsers yet (and not even remotely by IE11), so I'd vote no on it right now.

Unless a fallback was written.  But even then I don't think any browser has full support for the CSS Grid spec yet (most of it in chrome though)?

**Comment by knewter** [comment]
What @OvermindDL1 said. I'd love to be able to use grid but don't feel comfortable with it for at least another few months. It's *so close though*.
