### ISSUE TITLE
Add support for reactions

### ISSUE THREAD

**Issue by knewter** [dailydrip/firestorm#11]
Reactions (emoji, etc)
- User_id
- Emoji_name
- Does anyone know of an emoji library for elixir whatever that means?
  - https://github.com/mroth/exmoji probably
    - NOTE: This supports search yay

**Comment by agustif** [comment]
It would be helpful if ":" started a text search for emojis that the user could preview and select from the list. pressing enter would autocomplete the emoji.

Well, just like here kinda hahaha
