### ISSUE TITLE
Add github<->slack integration for #firestorm

### ISSUE THREAD

**Issue by knewter** [dailydrip/firestorm#18]
I made a request to @stevedomin to get our GitHub activity going into the channel. No clue if it's the sort of thing the elixir community wants to encourage on the slack since i believe it increases message volume, but since @trevoke mentioned it I figured I'd make an effort )

**Comment by knewter** [comment]
NOTE: this has nothing to do with the firestorm slackbot. On re-reading it, it seemed like it might give that impression. I'll go ahead and make an issue for that so it doesn't get left behind later, and put it at the 1.1 milestone

**Comment by stevedomin** [comment]
@knewter done!
