### ISSUE TITLE
Only link URLs that aren't markdown links

### ISSUE THREAD

**Issue by Trevoke** [dailydrip/firestorm#26]
I believe #14 created a defect that can be seen in this post:

https://firestorm-dogfood.herokuapp.com/categories/your-elixir-projects/threads/11#post-50

The raw text is a proper markdown link, which it looks like may have been markdown-rendered and then auto-linked, it's unclear.

**Comment by Trevoke** [comment]
Yes, I think there's an "oops" here.

https://firestorm-dogfood.herokuapp.com/categories/elixir/threads/6#post-43

![image](https://cloud.githubusercontent.com/assets/67913/23858069/b3b4d51a-07d5-11e7-9b33-2764ae566cfc.png)

**Comment by Trevoke** [comment]
Also, I *think* this is related --

https://firestorm-dogfood.herokuapp.com/categories/your-elixir-projects/threads/7#post-52

![image](https://cloud.githubusercontent.com/assets/67913/23858196/fbfdeece-07d5-11e7-8322-01878e54160b.png)

**Comment by knewter** [comment]
yeah I think I have a fix for it in a branch already derp. I just needed to get notifications finished.

**Comment by knewter** [comment]
![screenshot 2017-03-13 16 54 08](https://cloud.githubusercontent.com/assets/3829/23876913/b1b793aa-080d-11e7-860a-c88709b85bb2.png)

Looks like it fixed it, closing :)
