### ISSUE TITLE
Cannot easily refer to a comment from an external source

### ISSUE THREAD

**Issue by Trevoke** [dailydrip/firestorm#3]
I wanted to bring up something from Josh's comment in https://firestorm-dogfood.herokuapp.com/categories/your-elixir-projects/threads/11 in Slack and realized the best I could do was link to the thread itself, which makes referring to a particular source of information more difficult. 

What I expected was a link to the comment itself that would scroll to / highlight the post that I linked to.

**Comment by knewter** [comment]
OK, so this is a feature request for permalinks - I think we should have a `link` icon on each post for that and it's just the permalink to the post id in the thread. Thoughts? Once we add pagination this will require some modicum of effort to get right but not like it's brain surgery.

**Comment by Trevoke** [comment]
I can't think of any reason to make this any more complex, unless we want to consider something like "left-click to copy link to clipboard".

**Comment by SoreGums** [comment]
Only thing to consider is losing the whole thread as normal and scrolling to the post linked to. The xda dev forums only show the post and then you need to figure out where it is in the thread so you have all the context.

**Comment by knewter** [comment]
Closed in #20
