### ISSUE TITLE
Bug: A category with non-ascii characters can't be slugified properly

### ISSUE THREAD

**Issue by Trevoke** [dailydrip/firestorm#4]
https://firestorm-dogfood.herokuapp.com/categories/breaking/threads/9

**Comment by knewter** [comment]
This is down to the `slugger` library: https://github.com/h4cc/slugger

What should be the behaviour when using pinyin or otherwise not-trivial-to-sluggify characters? I'm inclined to believe that we should always just use the id if the slug is blank - easy to do, system already supports it.

**Comment by Trevoke** [comment]
I think that's probably good enough..

It looks like another way of doing it is as indicated here, but I don't think we'd get value out of this: http://stackoverflow.com/a/21186167/234025
