### ISSUE TITLE
Don't get an email when you reply by email

### ISSUE THREAD

**Issue by Trevoke** [dailydrip/firestorm#41]
I tested with this thread: https://firestorm-dogfood.herokuapp.com/categories/your-elixir-projects/threads/11

Josh posted https://firestorm-dogfood.herokuapp.com/categories/your-elixir-projects/threads/11#post-67 and I got an email, so I replied via email, which you can see, and then I got what I thought was a notification from that response... So I replied to *that* via email, and you can see how that's working out for us in the thread.

We should not be receiving the standard notification email for a reply we sent via email.

**Comment by knewter** [comment]
This is actually "don't get an email about your own posts" and I can just knock it out, one sec :)

**Comment by knewter** [comment]
OK I think it's fixed in 868fff8
