### ISSUE TITLE
Implement user pages / profile screen

### ISSUE THREAD

**Issue by knewter** [dailydrip/firestorm#59]

**Comment by agustif** [comment]
I was thinking the other day browsing elixir-forums how amazing would be to be able to know when @josevalim or other core-contributors say something...

I mean, I don't want to idolize anyone, but it's useful to keep tabs on top contributors of any community, usually they noise ratio is the best you can get to stay informed on lang/lib specifics

**Comment by knewter** [comment]
This is available since a couple of weeks ago so closing this...
