### ISSUE TITLE
Bug(?) with displayed name next to thread title

### ISSUE THREAD

**Issue by Trevoke** [dailydrip/firestorm#6]
## Here, the author is @digitalsatori and I'm the last person to have commented
![image](https://cloud.githubusercontent.com/assets/67913/23729080/05b33cc2-042e-11e7-95b6-1a04cf136d1c.png)

## Here, this person ( @kevin-dl ) is the author, not the last person who commented ( @knewter )
![image](https://cloud.githubusercontent.com/assets/67913/23729098/18f49c0e-042e-11e7-845c-8a0c75a77524.png)

## Here, I'm the author, and @knewter is the person who commented last
![image](https://cloud.githubusercontent.com/assets/67913/23729117/323acefe-042e-11e7-86f2-c35924164979.png)

I don't know what the intended behavior is, and I can't guess.

**Comment by knewter** [comment]
It should always be the person that started the thread. This is just wrong. Needs another test clearly!

**Comment by knewter** [comment]
Should be fixed by https://github.com/dailydrip/firestorm/commit/9877b6e227060caaea47bd2b281c1ad056b8447c
