### ISSUE TITLE
Bug with attachment?

### ISSUE THREAD

**Issue by Trevoke** [dailydrip/firestorm#7]
I tried to reply to a thread, typed a few letters, and clicked on the paperclip, and it submitted the few letters : https://firestorm-dogfood.herokuapp.com/categories/elixir/threads/6

**Comment by knewter** [comment]
This is yet-to-be-implemented. Hopefully this week. For now it's just a button so it submits the form...

**Comment by knewter** [comment]
Closing this issue in lieue of #12
