### ISSUE TITLE
Login on firestorm-dogfood.herokuapp.com broken

### ISSUE THREAD

**Issue by COLABORATI** [dailydrip/firestorm#72]
Trying to login via github gives me this error: 

#Ecto.Changeset<action: nil, changes: %{username: "COLABORATI"}, errors: [email: {"can't be blank", [validation: :required]}], data: #FirestormData.Commands.LoginOrRegisterFromGitHub<>, valid?: false>

Also the app takes very long to load.

**Comment by Trevoke** [comment]
The app takes long to load because heroku is spinning up the Dyno.

Your github account currently needs your email address to be public.
