### ISSUE TITLE
Decouple front-end code so we can use vuejs

### ISSUE THREAD

**Issue by COLABORATI** [dailydrip/firestorm#73]
I do not believe that elm is a good choice, details should not be [discussed](https://news.ycombinator.com/item?id=12906119) here, however I would like to see an app design where it is easy to replace the frontend by e.g. vuejs. 

Please keep this app frontend-agnostic so frontend devs can make their own decisions on frontend tools, thank you very much!

**Comment by knewter** [comment]
@COLABORATI good news - the app is going to by default just have an HTML/jquery frontend in the phoenix app, and the elm app will be a separate project that uses the Channels based API. I have some thoughts about how the store should work that are embedded in the API, but I'm also fine with someone submitting a REST-based API if that's what they want. If you'd like to chat about my thoughts on the store, I'll be writing them up once we hit 1.0 and I have a bit more time to put some names to some of the concepts, but tl;dr it makes a client crazy fast by intelligent pre-fetching.
