### ISSUE TITLE
Cannot log in with GitHub with blank email. Unfriendly flash notice

### ISSUE THREAD

**Issue by sngeth** [dailydrip/firestorm#77]
Hi I just found this project, decided to play around with it on the heroku dogfood deployment. I clicked Login with github, clicked authorized when the GitHub auth page came and it threw me this error

![image](https://cloud.githubusercontent.com/assets/575392/25730833/930a90fe-310e-11e7-85b2-248d3fa0a5c7.png)

Just realized my email wasn't displayed on GitHub, so I made it public. Log in worked.

That seemed to confuse me for a moment. Should we provide a more user friendly error (users shouldn't really be concerned about why a changeset fails in that much detail) ? I can tidy up this message if this is a good idea.

**Comment by theangryangel** [comment]
See #40

**Comment by sngeth** [comment]
Thanks, closing in favor existing issue above.
